//validation errors
const VALIDATION_ERROR = 'VALIDATION_ERROR';
const INVALID_PASSWORD = 'INVALID_PASSWORD';
const INVALID_EMAIL = 'INVALID_EMAIL';
const NOT_FOUNT_ERROR = 'NotFoundError';
const SALT_ROUNDS = 10;

module.exports={ 
  VALIDATION_ERROR, 
  INVALID_PASSWORD, 
  INVALID_EMAIL, 
  NOT_FOUNT_ERROR,
  SALT_ROUNDS
}

